/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TacticsGuideRouteImport } from './routes/tactics-guide'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowToReplyRouteImport } from './routes/how-to-reply'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EnRouteImport } from './routes/en'
import { Route as AiReplyGeneratorRouteImport } from './routes/ai-reply-generator'
import { Route as IndexRouteImport } from './routes/index'

const TacticsGuideRoute = TacticsGuideRouteImport.update({
  id: '/tactics-guide',
  path: '/tactics-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToReplyRoute = HowToReplyRouteImport.update({
  id: '/how-to-reply',
  path: '/how-to-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReplyGeneratorRoute = AiReplyGeneratorRouteImport.update({
  id: '/ai-reply-generator',
  path: '/ai-reply-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-reply-generator': typeof AiReplyGeneratorRoute
  '/en': typeof EnRoute
  '/history': typeof HistoryRoute
  '/how-to-reply': typeof HowToReplyRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/tactics-guide': typeof TacticsGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-reply-generator': typeof AiReplyGeneratorRoute
  '/en': typeof EnRoute
  '/history': typeof HistoryRoute
  '/how-to-reply': typeof HowToReplyRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/tactics-guide': typeof TacticsGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-reply-generator': typeof AiReplyGeneratorRoute
  '/en': typeof EnRoute
  '/history': typeof HistoryRoute
  '/how-to-reply': typeof HowToReplyRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/tactics-guide': typeof TacticsGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-reply-generator'
    | '/en'
    | '/history'
    | '/how-to-reply'
    | '/privacy'
    | '/settings'
    | '/tactics-guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-reply-generator'
    | '/en'
    | '/history'
    | '/how-to-reply'
    | '/privacy'
    | '/settings'
    | '/tactics-guide'
  id:
    | '__root__'
    | '/'
    | '/ai-reply-generator'
    | '/en'
    | '/history'
    | '/how-to-reply'
    | '/privacy'
    | '/settings'
    | '/tactics-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReplyGeneratorRoute: typeof AiReplyGeneratorRoute
  EnRoute: typeof EnRoute
  HistoryRoute: typeof HistoryRoute
  HowToReplyRoute: typeof HowToReplyRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TacticsGuideRoute: typeof TacticsGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tactics-guide': {
      id: '/tactics-guide'
      path: '/tactics-guide'
      fullPath: '/tactics-guide'
      preLoaderRoute: typeof TacticsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-reply': {
      id: '/how-to-reply'
      path: '/how-to-reply'
      fullPath: '/how-to-reply'
      preLoaderRoute: typeof HowToReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-reply-generator': {
      id: '/ai-reply-generator'
      path: '/ai-reply-generator'
      fullPath: '/ai-reply-generator'
      preLoaderRoute: typeof AiReplyGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReplyGeneratorRoute: AiReplyGeneratorRoute,
  EnRoute: EnRoute,
  HistoryRoute: HistoryRoute,
  HowToReplyRoute: HowToReplyRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TacticsGuideRoute: TacticsGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
